#!/bin/bash

#python ../tools/webidl_binder.py ../NanoVG.idl glue
emcc -s USE_GLFW=3 -s FULL_ES2=1 -I../../src ../NanoVGContext.cpp glue.cpp ../rgba.c ../../src/nanovg.c --post-js glue.js -o nanovg.js -DNANOVG_GLEW -DEMSCRIPTEN -O0
